/** Explore Victoria Falls Commerce Worker. Bind DB, PAYNOW_INTEGRATION_ID, PAYNOW_INTEGRATION_KEY, PAYNOW_RETURN_URL, PAYNOW_RESULT_URL. */
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json",...corsHeaders}});
const text=(d,s=200)=>new Response(d,{status:s,headers:corsHeaders});
const makeOrderId=()=>`EVF_${Date.now()}_${Math.random().toString(36).slice(2,8).toUpperCase()}`;
async function sha512(input){const b=new TextEncoder().encode(input),h=await crypto.subtle.digest("SHA-512",b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase()}
async function paynowHash(values,key){return sha512(values.join("")+key)}
async function getProducts(env){const r=await env.DB.prepare("SELECT * FROM products WHERE active = 1 ORDER BY sort_order ASC").all();return r.results||[]}
async function reserveInventory(env,orderId,products){for(const item of products){const r=await env.DB.prepare("UPDATE inventory SET stock_on_hand = stock_on_hand - ? WHERE product_id = ? AND variant_id = ? AND COALESCE(size, '') = COALESCE(?, '') AND stock_on_hand >= ?").bind(item.quantity,item.product_id,item.variant_id,item.size||"",item.quantity).run();if(!r.meta||r.meta.changes<1)throw new Error(`Insufficient stock for ${item.product_id} ${item.variant_id} ${item.size||""}`);await env.DB.prepare("INSERT INTO inventory_movements (movement_id, product_id, variant_id, size, quantity_change, reason, order_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))").bind(crypto.randomUUID(),item.product_id,item.variant_id,item.size||"",-item.quantity,"order_reserved",orderId).run()}}
async function createOrder(request,env){const body=await request.json();if(!Array.isArray(body.products)||!body.products.length)return json({error:"No products supplied"},400);const orderId=makeOrderId(),subtotal=Number(body.subtotal_amount||0),deliveryFee=Number(body.delivery_fee||0),total=Number(body.total_amount||subtotal+deliveryFee);await env.DB.prepare("INSERT INTO orders (order_id, keyword, source, currency, subtotal_amount, delivery_method, delivery_fee, total_amount, payment_status, fulfilment_status, shipment_status, customer_name, customer_phone, customer_email, delivery_address, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'created', 'unfulfilled', 'not_shipped', ?, ?, ?, ?, datetime('now'), datetime('now'))").bind(orderId,body.keyword||"VictoriaFalls",body.source||"website",body.currency||"USD",subtotal,body.delivery_method||"pickup",deliveryFee,total,body.customer_name||"",body.customer_phone||"",body.customer_email||"",body.delivery_address||"").run();for(const item of body.products){await env.DB.prepare("INSERT INTO order_items (item_id, order_id, product_id, product_name, variant_id, variant_label, size, quantity, unit_price, line_total, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))").bind(crypto.randomUUID(),orderId,item.product_id,item.name,item.variant_id||"",item.variant_label||"",item.size||"",Number(item.quantity),Number(item.unit_price),Number(item.line_total)).run()}try{await reserveInventory(env,orderId,body.products)}catch(err){await env.DB.prepare("UPDATE orders SET payment_status = 'cancelled', fulfilment_status = 'stock_failed', updated_at = datetime('now') WHERE order_id = ?").bind(orderId).run();return json({error:err.message,order_id:orderId},409)}return json({status:"created",order_id:orderId,total_amount:total,checkout_url:`/checkout.html?order_id=${orderId}`},201)}
async function initiatePaynow(request,env){const body=await request.json(),orderId=body.order_id,order=await env.DB.prepare("SELECT * FROM orders WHERE order_id = ?").bind(orderId).first();if(!order)return json({error:"Order not found"},404);const id=env.PAYNOW_INTEGRATION_ID,key=env.PAYNOW_INTEGRATION_KEY,reference=order.order_id,amount=Number(order.total_amount).toFixed(2),returnUrl=env.PAYNOW_RETURN_URL,resultUrl=env.PAYNOW_RESULT_URL,email=body.email||order.customer_email||"customer@example.com",additionalInfo=`Explore Victoria Falls ${reference}`,hash=await paynowHash([id,reference,amount,additionalInfo,returnUrl,resultUrl,"customer",email],key);const form=new URLSearchParams({id,reference,amount,additionalinfo:additionalInfo,returnurl:returnUrl,resulturl:resultUrl,authemail:email,status:"Message",hash});const response=await fetch("https://www.paynow.co.zw/interface/initiatetransaction",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form});const raw=await response.text();await env.DB.prepare("INSERT INTO payment_attempts (attempt_id, order_id, provider, request_amount, provider_response, created_at) VALUES (?, ?, 'paynow', ?, ?, datetime('now'))").bind(crypto.randomUUID(),orderId,amount,raw).run();return json({status:"initiated",order_id:orderId,provider_response:raw})}
async function paynowResult(request,env){const body=await request.text(),p=new URLSearchParams(body),reference=p.get("reference"),status=p.get("status");if(reference){const paymentStatus=String(status||"").toLowerCase()==="paid"?"paid":"pending";await env.DB.prepare("UPDATE orders SET payment_status = ?, paynow_status = ?, updated_at = datetime('now'), paid_at = CASE WHEN ? = 'paid' THEN datetime('now') ELSE paid_at END WHERE order_id = ?").bind(paymentStatus,status||"",paymentStatus,reference).run()}return text("OK")}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:corsHeaders});const url=new URL(request.url);try{if(url.pathname==="/api/products"&&request.method==="GET")return json(await getProducts(env));if(url.pathname==="/api/orders"&&request.method==="POST")return createOrder(request,env);if(url.pathname==="/api/paynow/initiate"&&request.method==="POST")return initiatePaynow(request,env);if(url.pathname==="/api/paynow/result"&&request.method==="POST")return paynowResult(request,env);return json({error:"Not found"},404)}catch(err){return json({error:err.message||"Worker error"},500)}}};